module HandsHelper
  
  def card_image(id)
    if id == "ac"
      name = "1.png"
    elsif id == "as"
      name = "2.png"
    elsif id == "ah"
      name = "3.png"
    elsif id == "ad"
      name = "4.png"
    elsif id == "kc"
      name = "5.png"
    elsif id == "ks"
      name = "6.png"
    elsif id == "kh"
      name = "7.png"
    elsif id == "kd"
      name = "8.png"
    elsif id == "qc"
      name = "9.png"
    elsif id == "qs"
      name = "10.png"
    elsif id == "qh"
      name = "11.png"
    elsif id == "qd"
      name = "12.png"
    elsif id == "jc"
      name = "13.png"
    elsif id == "js"
      name = "14.png"
    elsif id == "jh"
      name = "15.png"
    elsif id == "jd"
      name = "16.png"
    elsif id == "tc"
      name = "17.png"
    elsif id == "ts"
      name = "18.png"
    elsif id == "th"
      name = "19.png"
    elsif id == "td"
      name = "20.png"
    elsif id == "9c"
      name = "21.png"
    elsif id == "9s"
      name = "22.png"
    elsif id == "9h"
      name = "23.png"
    elsif id == "9d"
      name = "24.png"
    elsif id == "8c"
      name = "25.png"
    elsif id == "8s"
      name = "26.png"
    elsif id == "8h"
      name = "27.png"
    elsif id == "8d"
      name = "28.png"
    elsif id == "7c"
      name = "29.png"
    elsif id == "7s"
      name = "30.png"
    elsif id == "7h"
      name = "31.png"
    elsif id == "7d"
      name = "32.png"
    elsif id == "6c"
      name = "33.png"
    elsif id == "6s"
      name = "34.png"
    elsif id == "6h"
      name = "35.png"
    elsif id == "6d"
      name = "36.png"
    elsif id == "5c"
      name = "37.png"
    elsif id == "5s"
      name = "38.png"
    elsif id == "5h"
      name = "39.png"
    elsif id == "5d"
      name = "40.png"
    elsif id == "4c"
      name = "41.png"
    elsif id == "4s"
      name = "42.png"
    elsif id == "4h"
      name = "43.png"
    elsif id == "4d"
      name = "44.png"
    elsif id == "3c"
      name = "45.png"
    elsif id == "3s"
      name = "46.png"
    elsif id == "3h"
      name = "47.png"
    elsif id == "3d"
      name = "48.png"
    elsif id == "2c"
      name = "49.png"
    elsif id == "2s"
      name = "50.png"
    elsif id == "2h"
      name = "51.png"
    elsif id == "2d"
      name = "52.png"
    end
    
    return "/images/cards/"+name
  end
  
end
